[package]
org = "wso2healthcare"
name = "USCorePatientAPI"
version = "1.0.3"
export = ["USCorePatientAPI"]
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Patient","r4","uscore"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
