[package]
org = "wso2healthcare"
name = "EpicConnect"
version = "1.0.1"
export = ["EpicConnect"]
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Epic"]

[build-options]
observabilityIncluded = true
