[package]
org = "wso2healthcare"
name = "AthenaConnect"
version = "1.0.2"
export = ["AthenaConnect"]
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","AthenaHealth"]

[build-options]
observabilityIncluded = true
