[package]
org = "wso2healthcare"
name = "CernerConnect"
version = "1.0.2"
export = ["CernerConnect"]
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Cerner"]

[build-options]
observabilityIncluded = true
