[package]
org = "wso2healthcare"
name = "EpicConnect"
version = "1.0.2"
export = ["EpicConnect"]
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Epic"]

[build-options]
observabilityIncluded = true
