[package]
org = "wso2healthcare"
name = "MetadataAPI"
version = "1.0.1"
export = ["MetadataAPI.config","MetadataAPI.constants","MetadataAPI.handlers","MetadataAPI.models","MetadataAPI.samples"]
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Metadata"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
