[package]
org = "wso2healthcare"
name = "CernerConnect"
version = "1.0.0"
export = ["CernerConnect"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Cerner"]

[build-options]
observabilityIncluded = true
