[package]
org = "wso2healthcare"
name = "SmartConfigAPI"
version = "1.0.0"
export = ["SmartConfigAPI.config","SmartConfigAPI.constants","SmartConfigAPI.handlers","SmartConfigAPI.models"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","SMART"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
