[package]
org = "wso2healthcare"
name = "EpicConnect"
version = "1.0.0"
export = ["EpicConnect"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Epic"]

[build-options]
observabilityIncluded = true
