[package]
org = "wso2healthcare"
name = "AthenaConnect"
version = "1.0.0"
export = ["AthenaConnect"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","AthenaHealth"]

[build-options]
observabilityIncluded = true
